import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import LabelList from './shared/labelList'
import { useState } from 'react'

interface Output {
  document: string
  annotation: Annotation[] 
}

interface Annotation {
  start: number
  end: number
  label: string
  text: string
}

export default function Home() {
  const [labels, setLabels] = useState<string[]>([])
  const [inputLabel, setInputLabel] = useState("")
  const [confirmDocument, setConfirmDocument] = useState(false)
  const [output, setOutput] = useState<Output>({document:"",annotation:[]})
  return (
    <>
      <Head>
        <title>React App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <h2>Add new labels here:</h2>
          <div>
            <input onChange={e => setInputLabel(e.target.value)} />
            <button 
              style={{marginLeft:"10px"}}
              onClick={() => {
                console.log("button pressed");
                const newLabels = [...labels, inputLabel];
                if(labels.includes(inputLabel)){
                  alert("There's already a label with that name")
                }
                else{
                  setLabels(newLabels);
                }
              }} 
            >Add Label</button>
          </div>
          <LabelList labels={labels}/>
          <h2>Insert your document text here:</h2>
          <textarea
            id='document'
            readOnly={confirmDocument}
            value={output.document}
            rows={20}
            cols={60}
            onChange={e => {
              const res: Output = {document: e.target.value, annotation:[]}
              setOutput(res)
              console.log(res)
            }}
          />
          <button
            onClick={() => setConfirmDocument(true)}
          >Confirm Document</button>
          { 
            confirmDocument 
            ?? 
            <>
              <h1>Annotated document</h1>
              <p>{output.document}</p>
            </>
          }
        </div>
      </main>
    </>
  )
}
